# Generated by Django 5.2.4 on 2025-08-04 21:20

from django.db import migrations


def populate_new_profile(apps, schema_editor):
    """
    Searching data in old model profil and populating the
    new model profil of the new app profiles
    """
    OldProfileModelData = apps.get_model('oc_lettings_site', 'Profile')
    ActualProfile = apps.get_model('profiles', 'Profile')

    for profile0 in OldProfileModelData.objects.all():
        # Populate the new profile
        ActualProfile.objects.create(
            id = profile0.id,
            favorite_city = profile0.favorite_city,
            user = profile0.user
        )


def reverse(apps, schema_editor):
# Create the possibility to roll back more than this migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_new_profile, reverse)
    ]
