version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Install Poetry
build:
  image: latest
  jobs:
    post_create_environment:
      - pip install poetry

python:
  install:
    - method: poetry
      path: .
  version: "3.12"

# Configure the documentation build
build:
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - poetry install
    build:
      - poetry run sphinx-build -b html . _build/html
    post_build:
      - poetry run sphinx-build -b html . _build/html
      - poetry run sphinx-build -b dirhtml . _build/dirhtml
      - poetry run sphinx-build -b singlehtml . _build/singlehtml
      - poetry run sphinx-build -b latex . _build/latex
