version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Install your project and docs dependencies
python:
  install:
    - method: pip
      path: .             # install your Django project (so autodoc works)
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py