# Generated by Django 5.2.4 on 2025-08-04 20:33

from django.db import migrations


def populate_new_adress_leting(apps, schema_editor):
    """
    Searching data in old model address and letting and populating in the
    models letting and address of the new app lettings
    """
    OldAddressModelData = apps.get_model("oc_lettings_site", "Address")
    OldLettingModelData = apps.get_model("oc_lettings_site", "Letting")
    ActualAddress = apps.get_model('lettings', 'Address')
    ActualLetting = apps.get_model('lettings', 'Letting')

    for adress0 in OldAddressModelData.objects.all():
        # Populate the new address
        ActualAddress.objects.create(
            id = adress0.id,
            number = adress0.number,
            street = adress0.street,
            city = adress0.city,
            state =  adress0.state,
            zip_code = adress0.zip_code,
            country_iso_code = adress0.country_iso_code
        )

    for letting0 in OldLettingModelData.objects.all():
        # Populate the new letting
        old_adress_obj = ActualAddress.objects.get(id=letting0.address.id)
        ActualLetting.objects.create(
            id = letting0.id,
            title = letting0.title,
            address = old_adress_obj
        )


def reverse(apps, schema_editor):
# Create the possibility to roll back more than this migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_new_adress_leting, reverse)
    ]
