FROM python:3.12-slim

WORKDIR /app

# Prepare system dependencies for Poetry and your app
# The dependences for poetry must be shorter
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry

COPY pyproject.toml poetry.lock* /app/
# Configure Poetry to install dependencies
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-root

COPY . /app

# Declaring port
EXPOSE 8000
# commands after container launched
CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
