version: "3.9"

services:
  web:
    build:
      context: ../
      dockerfile: docker/dockerfile
    ports:
      - "8003:8000"
    volumes:
      - ../:/app
    command: python manage.py runserver 0.0.0.0:8000
