# Generated by Django 5.2.4 on 2025-08-10 07:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site',
         '0002_remove_letting_address_delete_address_delete_letting'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.DeleteModel(
                name='Profile',
            ),
            ],
            # You want to reuse the table, so don't drop it
            database_operations=[],
        )
    ]
