name: Django migration test

on:
  push:
    branches: [ "preprod" ]
  pull_request:
    branches: [ "preprod" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: python -m pip install --upgrade poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run python manage.py test


  jobs:
    environment:
      name: production
      #url: ${{ steps.deployment.outputs.page_url }}
      url: "https://glencho.casacam.net/"
      
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    
     