name: ci/cd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: python -m pip install --upgrade poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run python manage.py test

      - name: Check coverage
        run: |
          poetry run coverage test
          poetry run coverage report --fail-under=80

      - name: Lint with flake8
        run: |
          poetry run flake8 --exclude .venv,*/migrations/*,*/__pycache__/* .

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # Build image docke and push it to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/dockerfile
        push: true
        tags: glenllaci/oc-lettings-site:latest

    - name: Trigger deployment on Render.com
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
